name: HTML Linter CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install HTML Linter
        run: npm install -g htmlhint

      - name: Run HTML Linter
        run: htmlhint "**/*.html"
