name: Linter CI

on:  
  push:  
    branches:  
      - main  

jobs:  
  lint-check:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v3  

      - name: Install Dependencies  
        run: |  
          npm install -g htmlhint  
          npm install -g stylelint stylelint-config-standard  

      - name: Run HTML Linter  
        run: htmlhint "**/*.html"  

      - name: Run CSS Linter  
        run: stylelint "**/*.css"  
